# version: "3.9

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    command: sh -c "cd /app && pnpm install && pnpm nx serve frontend"

volumes:
  node_modules:
