# version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: infrastructures/docker/backend.Dockerfile
      args:
        APP_PORT: ${APP_PORT}        # Dockerfile へ渡す
    env_file: .env
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: infrastructures/docker/frontend.Dockerfile
    env_file: .env
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped

volumes:
  db-data:
