# docker-compose.dev.yml

# version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: infrastructures/docker/Dockerfile.dev
    volumes:
      - .:/monorepo
      - node_modules:/monorepo/node_modules
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"  # バックエンド
      - "5173:5173"  # フロントエンド (Vite)
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoreserve
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  node_modules:
  db-data:
