# docker-compose.yml

# version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/monorepo
    tty: true
    stdin_open: true
    command: bash
